# Generated by Django 5.1 on 2024-08-25 22:28

import banking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_account_account_number_alter_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(default=banking.models.generate_unique_reference_id, max_length=15),
        ),
    ]
