# Generated by Django 5.1 on 2024-09-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
